### ISSUE TITLE
DOM parsing should respect the proper charset

### ISSUE THREAD

**Issue by boonebgorges** [openlab-at-city-tech/openlab-attributions#1]
See http://redmine.citytech.cuny.edu/issues/3155#change-22441 and https://github.com/openlab-at-city-tech/openlab/commit/286cb088a51dfe299592ba731f447cfac44aabc7. 

I'm unsure whether we can simply make the same change to openlab-attributions, which might be installed in environments where different character encoding is used by MySQL. Should we first be looking at the charset registered with `$wpdb`, and then using that value to set the `'encoding'` flag? @Kuzmanov could you investigate this?

**Comment by Kuzmanov** [comment]
@boonebgorges `$wpdb->charset` is in different format than the one the browsers use (utf8mb4 vs utf-8).
Instead, we should be able to get the encoding from the `wp_options` table  with `get_option( 'blog_charset' )`.

Ex:
```
$encoding = get_option( 'blog_charset' );
@$doc->loadHTML( '<?xml encoding="' .  $encoding . '">' . $content );
```

**Comment by boonebgorges** [comment]
Excellent - great call, @Kuzmanov ! I've made the change.
